version: '3'

services:
  postgres:
    image: postgres:16
    container_name: musician-gear-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=musician_gear_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: musician-gear-backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - PORT=5000
      - JWT_SECRET=your_jwt_secret_key_here
      - JWT_EXPIRE=1d
      - REFRESH_TOKEN_EXPIRE=7d
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=musician_gear_tracker
      - DB_PORT=5432
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
    container_name: musician-gear-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data: